### ISSUE TITLE
investigate multi-replica configuration for orthanc container

### ISSUE THREAD

**Issue by digihunch** [digihunch/orthweb#14]
1. set replicase=3 for orthanc containers. [x]
2. rewire port mapping in docker compose ([ref](https://stackoverflow.com/questions/70516739/how-to-configure-port-mapping-for-replicated-containers-in-docker-compose)). [x]
3. reconfigure envoy proxy configuration to distribute traffic [x]
4. bring envoy proxy version to latest --> outstanding

**Comment by digihunch** [comment]
4. when envoy version is 1.23+, dicom client fails tls handshake with error below.
```
storescu: Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:340)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:186)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.dcm4che3.net.Connection.createTLSSocket(Connection.java:1190)
	at org.dcm4che3.net.Connection.connect(Connection.java:1077)
	at org.dcm4che3.net.ApplicationEntity.connect(ApplicationEntity.java:648)
	at org.dcm4che3.net.ApplicationEntity.connect(ApplicationEntity.java:668)
	at org.dcm4che3.tool.storescu.StoreSCU.open(StoreSCU.java:542)
	at org.dcm4che3.tool.storescu.StoreSCU.main(StoreSCU.java:285)
```
this has to do with the tls client library of dcm4che.
for now stick with 1.22.x until the fix is merged and released

**Comment by digihunch** [comment]
1. and 2. are configured in 698ad3d956f05f4d86a59a627820175f5724d9bc. the lb in envoy comes with round robin.
3. should implement:
- health check driven by envoy -> done in c5756d26d06e63b0d7d3c73a0bc50b00241794a4
- session affinity on http port and tcp port -> done in 17e4108f3e5c4e7ff227f60d3f8fbb44f86ec517

**Comment by digihunch** [comment]
will revisit when Envoy bug is fixed. otherwise issue resolved
